# Generated by Django 3.1.1 on 2021-02-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('deptID', models.AutoField(primary_key=True, serialize=False)),
                ('deptName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('empId', models.AutoField(primary_key=True, serialize=False)),
                ('empName', models.CharField(max_length=100)),
                ('dateJoin', models.DateField()),
                ('department', models.CharField(max_length=100)),
                ('imageFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
