# Generated by Django 3.1.1 on 2021-02-26 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RootApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='imageFileName',
        ),
    ]
