# Generated by Django 3.1.1 on 2021-02-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RootApp', '0002_remove_employees_imagefilename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('userPass', models.CharField(max_length=1000)),
            ],
        ),
    ]
